AllCops:
  Exclude:
    - './Gemfile'
    - './Rakefile'
    - './Guardfile'
    - './secure_headers.gemspec'
    - './spec/spec_helper.rb'
    - './vendor/bundle/**/*'
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml
