language: ruby

rvm:
  - ruby-head
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm:
      - jruby-head
      - ruby-head
  fast_finish: true

before_install: gem update bundler

sudo: false
cache: bundler
