language: ruby

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.3
  - 2.2
  - 2.1
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head

before_install: gem update bundler
bundler_args: --without guard -j 3

sudo: false
cache: bundler
